name: Scheduled Workflow
on: 
  schedule:
    - cron: '*/5 * * * *' #every 5 minutes
jobs:  
  show-info:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: test
      - name: Info
        run: |
          echo "This is a push event on all the branches"
